# Generated by Django 3.2.7 on 2021-10-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210918_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='details',
            field=models.CharField(max_length=300),
        ),
    ]
